spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8341/verby_main?serverTimezone=Asia/Seoul
    username: root
    password: root

  redis:
    host: localhost
    port: 8342

  session:
    store-type: redis

  devtools:
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO