version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.13
  aws-code-deploy: circleci/aws-code-deploy@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk
        environment:
          DATABASE_URL: ${VERBY_MAIN_URL)

    resource_class: medium

    steps:
      - checkout

      - run:
          command: ./gradlew clean build

      - run:
          command: |
            zip verby-rest-api.zip -r ./*
            mkdir -p deploy
            mv verby-rest-api.zip deploy/verby-rest-api.zip

      - persist_to_workspace:
          root: .
          paths:
            - deploy

  deploy:
    docker:
      - image: circleci/python:2.7

    steps:
      - attach_workspace:
          at: .

      - aws-s3/copy:
          from: deploy/*
          to: 's3://verby-deploy'
          aws-region: AWS_DEFAULT_REGION

      - aws-code-deploy/deploy-bundle:
          application-name: verby-server
          deployment-group: verby-group
          deployment-config: CodeDeployDefault.AllAtOnce
          bundle-bucket: verby-deploy
          bundle-key: verby-rest-api
          bundle-type: zip

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          context: AWS
          requires:
            - build