version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.13
  aws-code-deploy: circleci/aws-code-deploy@0.0.12

jobs:
  build:
    docker:
      - image: openjdk:17-alpine
        environment:
          DATABASE_URL: ${VERBY_MAIN_URL)

    resource_class: medium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          command: ./gradlew clean build

      - run:
          command: zip -r verby-rest-api *
            mkdir -p deploy
            mv verby-rest-api.zip deploy/verby-rest-api.zip

  deploy:
    docker:
      - image: circleci/python:2.7

    steps:
      - attach_workspace:
          at: .

      - aws-s3/copy:
          from: deploy/*
          to: 's3://verby-deploy'
          aws-region: AWS_DEFAULT_REGION

      - aws-code-deploy/deploy-bundle:
          application-name: EC2CodeDeployTest
            deployment-group: EC2CodeDeployTestGroup
            deployment-config: CodeDeployDefault.AllAtOnce
            bundle-bucket: verby-deploy
            bundle-key: verby-rest-api
            bundle-type: zip

    executor:
    on:
      repo: verby-korea/verby-rest-api
      branch: master

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          context: AWS
          requires:
            - build